title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:    User
  repo:     Test1

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: Create a task list
  description: A task list creates checkboxes for people with access in a repository to check off.
  event: Add a comment to this issue, using Markdown to create a list of items to complete. Your task can include any tasks you wish, or you can use this example(comment below)
  actions: Comment will be posted
  - type: reopenIssue

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
 - title: Turn on GitHub Pages
  description: Now let's turn our focus to the content of your portfolio. Because this portfolio will display as a static web page, you'll need to enable GitHub Pages.
  event: In the GitHub Pages section, use the Select source drop-down menu to select master as your GitHub Pages publishing source.
  actions: Page will be published
  - type: enablePages

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
 - title: Add headers
  description: As you saw on your website, your portfolio doesn't have much content yet. We'll learn how to edit the file in this pull request to incorporate some Markdown headers.
  event: In this pull request, click the Files changed tab.
In the upper right corner of the file view, click the small pencil ✏️ icon for the file titled _includes/01-name.md.
On the Edit file tab, add a "#" before the content to make it an H1 Header. You can add more headers, using one to six "#" characters.
Above your new content, click Preview changes.
At the bottom of the page, type a short, meaningful commit message that describes the change you made to the file.
Click Commit changes.
  actions: Header will be added
  - type: htmlContainsTag

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
 - title: Add a list
  description: In this pull request, you'll learn about lists and emoji. You'll also list a few details in your resume.
  event: Edit the _includes/04-lists.md in this pull request.
Create a markdown list in the file. It can be ordered or unordered.
Commit your changes.
  actions: List will be created
  - type: htmlContainsTag

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
 - title: Use emphasis
  description: Nice list! You can merge this pull request when you're ready.
  event: Click Merge pull request below.
  actions: Branches will be merged
  - type: mergeBranch

